print('Sum :',2+35)
print('Difference :',77-3)
print('Product :',2*7)
print('Quotient :',4/2)
print('Exponential :',2**4)
print('Floor Division :',4//2)
print('Remainder :',5%3)
print('Multiple Operations :',3+7-2)
print ('BODMAS Rule :',(3*2)/6*5+4-2)
print('Arithmetic Operations in Python :\n1.Sum : Symbol: +\n2.Difference : Symbol: -\n3.Product : Symbol: *\n4.Division : Symbol: /\n5.Exponential : Symbol: **\n6.Floor Division : Symbol: //\n7.Modulus : Symbol: %\n8.BODMAS Rule : Symbol: ()/*+-')
